title: Dataset Template for Publishing Affect Data
description: An example dataset template created following the TRRRACED Protocol for reproducible, replicable, and reusable experiments and data in the Affective Computing domain. 

publisher_text: 
publisher_url: 

license_text:
license_url: 

frequency:

certificate_embed: <script src=></script>
